spring:
  application:
    name: customer-service
  h2:
    console:
      enabled: true
  datasource:
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    embedded-database-connection: h2
    url: jdbc:h2:file:./data/sql
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      mode: always
server:
  servlet:
    context-path: /customer
