INSERT INTO CUSTOMER (AGE, NAME) VALUES (34, 'Vision');
INSERT INTO CUSTOMER (AGE, NAME) VALUES (33, 'Scarlet');
INSERT INTO CUSTOMER (AGE, NAME) VALUES (5, 'Billy');
INSERT INTO CUSTOMER (AGE, NAME) VALUES (5, 'Tommy');
